### ISSUE TITLE
GitHub Pages erstellen

### ISSUE THREAD

**Issue by christophhandel** [htl-leonding-project/2022-4ahif-leo-competition#15]

**Comment by joachimPelzederHTL** [comment]
Rebuild GH-Pages d071644109fc27417a5b4ef6399460476e3f879b

**Comment by joachimPelzederHTL** [comment]
Rebuild GH-Pages 6f9d0b189e367ac9d95dd0cfc5c9410c806b1ab5

**Comment by joachimPelzederHTL** [comment]
Removed gh-pages-folder 6a0f085061ea46fee353ebeebb0995e516bb7200

**Comment by joachimPelzederHTL** [comment]
Fixed Problems with scripts cf1d42f6e86858486b7e54ebf85c9450e517c384

**Comment by joachimPelzederHTL** [comment]
Rebuild gh-pages 6bea57df41978efb40ea1ad99a14a3e7fbd730b5
