### ISSUE TITLE
Projectpresentation

### ISSUE THREAD

**Issue by joachimPelzederHTL** [htl-leonding-project/2022-4ahif-leo-competition#22]

**Comment by joachimPelzederHTL** [comment]
https://mrduguo.github.io/asciidoctor.org/docs/asciidoctor-revealjs/

**Comment by christophhandel** [comment]
79046d7de6d80ef4d016ead6081877c9cdba5c89

**Comment by christophhandel** [comment]
72222100a2a40a57c45993670f7304f9ac68ce30

**Comment by christophhandel** [comment]
c1b59495062bce8e3c3c4674f7aed2e51f32bbe0

**Comment by christophhandel** [comment]
7826728b35fd775fc070cc12af8292990960636e

**Comment by joachimPelzederHTL** [comment]
-> Alles auf YouTrack
